### ISSUE TITLE
aib workflow fails with error 400

### ISSUE THREAD

**Issue by florian-ried** [pauldotyu/azure-wvd#2]
After running the Azure Image Builder Workflow i get the following error

![image](https://user-images.githubusercontent.com/95634472/149201870-6afd5821-f4a4-4ee1-8ecc-caa5885493f1.png)

How could I fix this error? Many thanks in advance.

**Comment by pauldotyu** [comment]
@florian-ried from the looks of the error message, it appears that the "galleryImageId" is missing the subscription ID. You will need to add it as a GitHub secret like this doc describes. 

https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-environment

The secret is used in this line of code in the GitHub Action: https://github.com/pauldotyu/azure-avdops-terraform/blob/3d82dee9da1460416f582899a664256aa5f27978/.github/workflows/azure-image-builder.yml#L60

**Comment by florian-ried** [comment]
Thank you so much!
That works for me :)
